### ISSUE TITLE
Password Storage Cheat Sheet error

### ISSUE THREAD

**Issue by ArtemNikolaev** [OWASP/www-project-cheat-sheets#20]
Link to `Password Storage Cheat Sheet | OWASP` https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet#Use_a_cryptographically_strong_credential-specific_salt don't work

when I serch OWASP site for `password` I see this link on first place, but when I try to open, I see error

**Comment by ThunderSon** [comment]
Kindly refer to the official website of the cheatsheets: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
We are currently studying what to do for a seamless experience, instead of facing those 404.
Thank you for reaching out! 😄
