### ISSUE TITLE
invalid url with the OWASP cheat sheet series link

### ISSUE THREAD

**Issue by rushendraChowdary** [OWASP/www-project-cheat-sheets#6]
https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_Introduction.html 

in the above link, if i click on OWASP Cheet Series link the url it is giving me is 
https://wwww2.owasp.org/www-project-cheat-sheets/ rather than 
https://www2.owasp.org/www-project-cheat-sheets/. please look into it and change it to appropriate link.
I'm sorry if i am posting it in the wrong repo. I am just a beginner to all this. Thank you.

**Comment by mikemccamon** [comment]
I just did a commit that fixed this and made several other links relative to the site and not hard coded to www.owasp....
