### ISSUE TITLE
Session diagram image is missing

### ISSUE THREAD

**Issue by mommcilo** [OWASP/www-project-cheat-sheets#8]
https://owasp.org/www-project-cheat-sheets/cheatsheets/Session_Management_Cheat_Sheet.html

![sessionDiagram](https://user-images.githubusercontent.com/1678074/73058856-cf2aec00-3e94-11ea-8452-bca266ff6c98.PNG)

**Comment by ThunderSon** [comment]
Thank you for bringing this up! This has been fixed 😄 Enjoy reading the cheat sheets, and if you ever find anything else, let us know!

**Comment by ThunderSon** [comment]
@mommcilo I saw you did a commit. Currently, the official cheat sheets is hosted on cheatsheetseries.owasp.org/ and not on the main www website. This is still a work in progress 😄

**Comment by mommcilo** [comment]
> @mommcilo I saw you did a commit. Currently, the official cheat sheets is hosted on cheatsheetseries.owasp.org/ and not on the main www website. This is still a work in progress 😄

Ha ha I didn't know that 😄 😄 😄
