### ISSUE TITLE
HTTP Request Header Injection vs HTTP Response Splitting

### ISSUE THREAD

**Issue by JLLeitschuh** [OWASP/www-project-cheat-sheets#9]
Http Request Splitting vulnerability is different from HTTP Response Splitting because it enables an attacker to control the outgoing request from a server. Unlike HTTP Response Splitting, this vulnerability enables SSRF because an attacker is able to piggyback on an existing legitimate request and add their own request on top of that.

I've written up a better example of this here:
https://github.com/netty/netty/issues/10059

I've got a CVE pending with this issue. Unfortunately, CWE-113 only seems to really address HTTP Response Splitting, not this vulnerability.

Here's an example detailing this sort of vulnerability in Python back in 2016.
http://blog.blindspotsecurity.com/2016/06/advisory-http-header-injection-in.html

**Comment by ThunderSon** [comment]
Can you please link to the location of the issue? This will be tackled in the CheatSheets project over here: https://github.com/OWASP/CheatSheetSeries
Thank you for reaching out!

**Comment by JLLeitschuh** [comment]
@ThunderSon would you be willing to move this issue there (using GitHub's 'transfer issue' feature?

Can you elaborate on what you mean by 'link to the location of the issue'?

There really isn't anywhere to link to because there currently isn't anywhere discussing HTTP Request Splitting (yet).
https://owasp.org/www-community/attacks/HTTP_Response_Splitting

**Comment by ThunderSon** [comment]
Sure thing. I'll transfer it tomorrow.
What Cheatsheet is this missing in, and which section specifically are you targeting? Just to make it a bit faster for me to tackle this.

**Comment by JLLeitschuh** [comment]
> ## HTTP _Request_ Splitting
> 
> This vulnerability is different from HTTP _Response_ Splitting because in this case, the user supplied data is being used to create another outgoing HTTP Request. One example of this would be a microarchitecture based infrastructure where the incoming request is relayed back out to an internal service.
> 
> When CRLF injection attacks exists here, the impact can also be quite nasty.
> 
> Let's take the following server example (this vulnerability **has not & does not** exist in Ratpack, this is just an example).
> 
> ```java
> // Not a real vulnerable example. Ratpack has never been vulnerable to HTTP Request Splitting
> RatpackServer startedServer = RatpackServer.start(server -> {
>     server.handlers(chain -> chain.all(ctx -> {
>         // User supplied query parameter
>         String header = ctx.getRequest().getQueryParams().get("header");
>         HttpClient client = ctx.get(HttpClient.class);
>         URI localhost = URI.create("http://localhost:12345");
>         client
>             .get(localhost, spec -> {
>                 spec.getHeaders().add("the-header", header);
>             })
>             .onError(Throwable::printStackTrace)
>             .then(response -> ctx.render(response.getBody().getText()));
>     }));
> });
> ```
> 
>  If, in this example, RatPack had header validation disabled for building outgoing requests an attacker would be able to control the outgoing HTTP request and inject their own additional requests.
> 
> For example, by sending the following in the `header` parameter (assume newlines are `\r\n`):
> 
> Note: `Connection: Keep-Alive` is used to keep the connection open so another request can be stuffed in.
> ```
> Connection: Keep-Alive
> 
> 
> POST /hello/super-secret HTTP/1.1
> Host: 127.0.0.1
> Content-Length: 31
> 
> {\"new\":\"json\",\"content\":\"here\"}
> 
> 
> ```
> 
> Here, the attacker is able to stuff an additional request into the GET request allowing the attacker to manipulate internal endpoints that they would normally be unable to control. This is also known as [Server Side Request Forgery](https://owasp.org/www-community/attacks/Server_Side_Request_Forgery).
> 
> This is a real example of a vulnerability that I've actually found in a project (patch and CVE pending).
>
> \- https://github.com/netty/netty/issues/10059

Basically, the current state is that HTTP Response Splitting is handled, but we're missing information about HTTP Request Splitting.

**Comment by JLLeitschuh** [comment]
I just chatted with James Kettle about this, the proper term for what I'm talking about is actually 'HTTP Request Header Injection'

**Comment by ThunderSon** [comment]
This issue is to be handled in the `www-community` repository.
